import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// Workers Builds → GitHub Actions → local git → dev.
function resolveSha() {
  const fromEnv = process.env.WORKERS_CI_COMMIT_SHA || process.env.GITHUB_SHA || "";
  const trimmed = fromEnv.trim();
  if (trimmed) return trimmed.slice(0, 7);
  try {
    const sha = execSync("git rev-parse --short=7 HEAD", { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
    if (sha) return sha.slice(0, 7);
  } catch {
    // Fresh checkout without git history.
  }
  return "dev";
}

const sha = resolveSha();
const built = new Date().toISOString();
const out = join(dirname(fileURLToPath(import.meta.url)), "..", "worker", "version.generated.ts");
const source = `// Generated by scripts/write-version.mjs. Do not edit.
export const VERSION_SHA = ${JSON.stringify(sha)};
export const VERSION_BUILT = ${JSON.stringify(built)};
`;

writeFileSync(out, source);
